#!/usr/bin/env bash

[[ -n "${_base_repo_installer_template_sourced:-}" ]] && return 0
_base_repo_installer_template_sourced=1
readonly _base_repo_installer_template_sourced

base_repo_installer_template_usage() {
    cat <<'EOF'
Usage:
  basectl repo installer-template [path] [options]

Options:
  --print, --stdout             Print the maintained template to stdout instead of writing a file.
  --repo <owner/name>           GitHub repository for --pr. Defaults to the target origin remote.
  --pr                          Commit the generated installer template on a branch and open a draft pull request.
  --dry-run                     Print planned changes without applying them.
  -v                            Enable DEBUG logging for this subcommand.
  -h, --help                    Show this help text.

Writes the maintained project installer template to path, or to ./install.sh
when path is omitted. Use --print to inspect or pipe the template.
EOF
}

base_repo_installer_template_path() {
    [[ -n "${BASE_HOME:-}" ]] || {
        log_error "BASE_HOME is required to locate the project installer template."
        return 1
    }

    printf '%s/templates/project-install.sh\n' "$BASE_HOME"
}

base_repo_print_installer_template() {
    local template

    template="$(base_repo_installer_template_path)" || return 1
    [[ -f "$template" ]] || {
        log_error "Project installer template was not found at '$template'."
        return 1
    }

    cat "$template"
}

base_repo_write_installer_template() {
    local dry_run="$1"
    local target="$2"
    local template

    template="$(base_repo_installer_template_path)" || return 1
    [[ -f "$template" ]] || {
        log_error "Project installer template was not found at '$template'."
        return 1
    }

    base_repo_write_executable_stream "$dry_run" "$target" < "$template"
}

base_repo_create_installer_template_pr_body() {
    local path="$1"
    local repo="$2"

    cat <<EOF
## Summary

- Add the maintained Base project installer template.

## Validation

- Not run. Generated installer-template change only.

Generated by:

\`\`\`bash
basectl repo installer-template $(base_repo_pretty_arg "$path") --repo $repo --pr
\`\`\`
EOF
}

base_repo_finish_installer_template_pr() {
    local dry_run="$1"
    local target_path="$2"
    local root="$3"
    local repo="$4"
    local branch="$5"
    local default_branch="$6"
    local rel_path="$7"
    local body_file status

    if [[ "$dry_run" == "1" ]]; then
        base_repo_finish_generated_pr \
            "$dry_run" \
            "$root" \
            "$repo" \
            "$branch" \
            "$default_branch" \
            "Add Base installer template" \
            "installer template file" \
            "Add Base installer template" \
            "" \
            "$rel_path"
        return $?
    fi

    std_make_temp_file body_file base-repo-installer-template-pr || {
        log_error "Failed to create a temporary pull request body file."
        return 1
    }
    base_repo_create_installer_template_pr_body "$target_path" "$repo" > "$body_file"
    base_repo_finish_generated_pr \
        "$dry_run" \
        "$root" \
        "$repo" \
        "$branch" \
        "$default_branch" \
        "Add Base installer template" \
        "installer template file" \
        "Add Base installer template" \
        "$body_file" \
        "$rel_path"
    status=$?
    rm -f "$body_file"
    return "$status"
}

base_repo_installer_template() {
    local create_pr=0
    local dry_run=0
    local github_repo=""
    local path=""
    local print_template=0
    local pr_branch=""
    local pr_default_branch=""
    local rel_path=""
    local repo_name=""
    local root=""

    while (($#)); do
        case "$1" in
            -h|--help|help)
                base_repo_installer_template_usage
                return 0
                ;;
            --repo)
                [[ -n "${2:-}" ]] || {
                    base_repo_installer_template_usage_error "Option '--repo' requires an argument."
                    return $?
                }
                github_repo="$2"
                shift 2
                ;;
            --repo=*)
                github_repo="${1#--repo=}"
                [[ -n "$github_repo" ]] || {
                    base_repo_installer_template_usage_error "Option '--repo' requires an argument."
                    return $?
                }
                shift
                ;;
            --print|--stdout)
                print_template=1
                shift
                ;;
            --pr)
                create_pr=1
                shift
                ;;
            --dry-run)
                dry_run=1
                shift
                ;;
            -v)
                set_log_level DEBUG
                export LOG_DEBUG=1
                shift
                ;;
            -*)
                base_repo_installer_template_usage_error "Unknown repo installer-template option '$1'."
                return $?
                ;;
            *)
                if [[ -n "$path" ]]; then
                    base_repo_installer_template_usage_error "The 'repo installer-template' command accepts at most one path."
                    return $?
                fi
                path="$1"
                shift
                ;;
        esac
    done

    if ((print_template)); then
        if ((create_pr)); then
            base_repo_installer_template_usage_error "Option '--print' cannot be used with --pr."
            return $?
        fi
        if [[ -n "$path" ]]; then
            base_repo_installer_template_usage_error "Option '--print' cannot be used with a path."
            return $?
        fi
        base_repo_print_installer_template
        return $?
    fi

    [[ -n "$path" ]] || path="install.sh"

    path="$(base_repo_target_path "$path")"
    root="$(dirname -- "$path")"
    repo_name="$(basename -- "$root")"

    if ((create_pr)); then
        if [[ -z "$github_repo" ]]; then
            github_repo="$(base_repo_infer_github_repo "$root" || true)"
        fi
        [[ -n "$github_repo" ]] || {
            base_repo_installer_template_usage_error "Option '--pr' requires --repo <owner/name> or an inferable GitHub origin remote."
            return $?
        }

        repo_name="${github_repo#*/}"
        pr_branch="$(base_repo_helper_pr_branch_name "installer-template" "$repo_name")"
        if [[ "$dry_run" == "1" ]]; then
            pr_default_branch="<default branch>"
            rel_path="$(basename -- "$path")"
        else
            base_repo_require_pr_worktree "$root" "repo installer-template --pr" || return 1
            pr_default_branch="$(base_repo_default_branch_for_pr "$github_repo")" || return 1
            rel_path="$(base_repo_relative_path_under_root "$root" "$path")" || {
                log_error "repo installer-template --pr expects path to be inside '$root'."
                return 1
            }
        fi
        base_repo_prepare_pr_branch "$dry_run" "$root" "$pr_branch" "$pr_default_branch" "repo installer-template --pr" || return 1
    fi

    base_repo_write_installer_template "$dry_run" "$path" || return $?
    if ((create_pr)); then
        base_repo_finish_installer_template_pr \
            "$dry_run" \
            "$path" \
            "$root" \
            "$github_repo" \
            "$pr_branch" \
            "$pr_default_branch" \
            "$rel_path"
        return $?
    fi
    if [[ "$dry_run" != "1" ]]; then
        base_repo_print_review_hint "$(dirname -- "$path")"
    fi
}
