from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from base_setup.manifest_model import BaseManifest


__all__ = (
    "CLASSIFICATIONS",
    "DevenvCompatibilityReport",
    "DevenvFieldClassification",
    "add_artifact_fields",
    "add_ide_fields",
    "add_project_owned_fields",
    "add_python_fields",
    "build_devenv_report",
    "devenv_report_to_json",
    "dumps_devenv_report_json",
    "field_to_json",
    "print_devenv_report_text",
    "summary_counts",
)


CLASSIFICATIONS = ("supported", "unsupported", "lossy", "project-owned")


@dataclass(frozen=True)
class DevenvFieldClassification:
    field: str
    classification: str
    reason: str


@dataclass(frozen=True)
class DevenvCompatibilityReport:
    project: str
    manifest_path: Path
    fields: tuple[DevenvFieldClassification, ...]


def build_devenv_report(manifest: BaseManifest) -> DevenvCompatibilityReport:
    fields: list[DevenvFieldClassification] = [
        DevenvFieldClassification(
            field="project.name",
            classification="supported",
            reason="The project name can be used as human-facing devenv metadata.",
        )
    ]

    if manifest.brewfile is not None:
        fields.append(
            DevenvFieldClassification(
                field="brewfile",
                classification="unsupported",
                reason="Brewfile is Homebrew-specific and is not translated to Nix packages.",
            )
        )
    if manifest.mise is not None:
        fields.append(
            DevenvFieldClassification(
                field="mise",
                classification="project-owned",
                reason="Project-owned mise configuration can coexist with devenv but is not generated by Base.",
            )
        )
    add_python_fields(manifest, fields)
    add_ide_fields(manifest, fields)
    add_artifact_fields(manifest, fields)
    add_project_owned_fields(manifest, fields)

    return DevenvCompatibilityReport(
        project=manifest.project_name,
        manifest_path=manifest.path,
        fields=tuple(fields),
    )


def add_python_fields(manifest: BaseManifest, fields: list[DevenvFieldClassification]) -> None:
    if manifest.python.manager is not None:
        fields.append(
            DevenvFieldClassification(
                field="python.manager",
                classification="lossy",
                reason="Python manager hints may inform devenv design, but Base cannot map them losslessly.",
            )
        )
    if manifest.python.requires_python is not None:
        fields.append(
            DevenvFieldClassification(
                field="python.requires_python",
                classification="lossy",
                reason="Python version constraints may inform a Nix Python package selection but need explicit policy.",
            )
        )
    if manifest.python.venv_location != "project":
        fields.append(
            DevenvFieldClassification(
                field="python.venv_location",
                classification="unsupported",
                reason="Base-managed external virtualenv state is host-local and is not represented in devenv output.",
            )
        )


def add_ide_fields(manifest: BaseManifest, fields: list[DevenvFieldClassification]) -> None:
    for ide_name in sorted(manifest.ide):
        fields.append(
            DevenvFieldClassification(
                field=f"ide.{ide_name}",
                classification="unsupported",
                reason="IDE customizations are editor state and are not represented in Nix/devenv output.",
            )
        )


def add_artifact_fields(manifest: BaseManifest, fields: list[DevenvFieldClassification]) -> None:
    for index, artifact in enumerate(manifest.artifacts, start=1):
        fields.append(
            DevenvFieldClassification(
                field=f"artifacts[{index}]",
                classification="lossy",
                reason=(
                    f"Base artifact {artifact.artifact_type}/{artifact.name} "
                    "would require an explicit nixpkgs or devenv package mapping."
                ),
            )
        )


def add_project_owned_fields(manifest: BaseManifest, fields: list[DevenvFieldClassification]) -> None:
    if manifest.test is not None:
        fields.append(
            DevenvFieldClassification(
                field="test",
                classification="project-owned",
                reason=(
                    "Test commands stay in the project manifest and should be "
                    "invoked through Base or project tooling."
                ),
            )
        )
    if manifest.commands:
        fields.append(
            DevenvFieldClassification(
                field="commands",
                classification="project-owned",
                reason="Project commands remain project-owned shell contracts.",
            )
        )
    if manifest.health.required_env:
        fields.append(
            DevenvFieldClassification(
                field="health.required_env",
                classification="project-owned",
                reason="Required environment variables describe local readiness, not Nix secrets.",
            )
        )
    if manifest.health.required_ports:
        fields.append(
            DevenvFieldClassification(
                field="health.required_ports",
                classification="project-owned",
                reason="Port health checks remain Base diagnostics.",
            )
        )
    if manifest.activate.source:
        fields.append(
            DevenvFieldClassification(
                field="activate.source",
                classification="project-owned",
                reason="Activation source scripts remain interactive project shell behavior.",
            )
        )
    if manifest.build is not None:
        fields.append(
            DevenvFieldClassification(
                field="build",
                classification="project-owned",
                reason="Build targets remain project-owned commands.",
            )
        )
    if manifest.demo is not None:
        fields.append(
            DevenvFieldClassification(
                field="demo",
                classification="project-owned",
                reason="Demo scripts remain project-owned executable walkthroughs.",
            )
        )


def devenv_report_to_json(report: DevenvCompatibilityReport) -> dict[str, Any]:
    return {
        "schema_version": 1,
        "project": report.project,
        "manifest_path": str(report.manifest_path),
        "target": "nix/devenv",
        "summary": summary_counts(report.fields),
        "fields": [field_to_json(field) for field in report.fields],
    }


def field_to_json(field: DevenvFieldClassification) -> dict[str, str]:
    return {
        "field": field.field,
        "classification": field.classification,
        "reason": field.reason,
    }


def summary_counts(fields: tuple[DevenvFieldClassification, ...]) -> dict[str, int]:
    return {
        classification: sum(1 for field in fields if field.classification == classification)
        for classification in CLASSIFICATIONS
    }


def dumps_devenv_report_json(report: DevenvCompatibilityReport) -> str:
    return json.dumps(devenv_report_to_json(report), indent=2, sort_keys=True) + "\n"


def print_devenv_report_text(report: DevenvCompatibilityReport) -> None:
    print(f"Nix/devenv compatibility for project '{report.project}'")
    print(f"Manifest: {report.manifest_path}")
    print()
    print(f"{'FIELD':<24} {'CLASSIFICATION':<14} REASON")
    for field in report.fields:
        print(f"{field.field:<24} {field.classification:<14} {field.reason}")
